import {writeFileSync,readFileSync} from 'node:fs';
import {createServer} from 'vite';
import {chromium} from 'playwright';
const root='art/blender/generated/character-module-v1/review';
const styles=JSON.parse(readFileSync('shared/character-styles.json')).styles;
const html=`<!doctype html><meta charset="UTF-8"><title>LepakMamak — Character wardrobe</title><style>*{box-sizing:border-box}body{margin:0;padding:42px;background:#102e29;color:#f5e6c9;font:15px system-ui}header{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid #657764;padding-bottom:20px;margin-bottom:24px}h1{font-size:34px;letter-spacing:-1px;margin:7px 0}header p{margin:0;color:#b4c8b7}small{font-size:11px;letter-spacing:2px;color:#d5bf87}h2{font-size:21px;margin:30px 0 14px}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}figure{margin:0;border:1px solid #607668;border-radius:12px;overflow:hidden;background:#213f35}img{display:block;width:100%;aspect-ratio:1;object-fit:cover}figcaption{padding:12px 5px;text-align:center;font-weight:600;font-size:14px}footer{margin-top:26px;font-size:12px;color:#b4c8b7}</style><header><div><small>LEPAKMAMAK · BLENDER CHARACTER MODULE</small><h1>36 gaya. Satu wardrobe.</h1><p>Rambut lelaki, rambut perempuan & tudung</p></div><small>MODEL THUMBNAILS · V1</small></header>${[['male','Rambut lelaki'],['female','Rambut perempuan'],['tudung','Tudung']].map(([cat,title])=>`<h2>${title} <small>12 GAYA</small></h2><div class="grid">${styles.filter(s=>s.category===cat).map(s=>`<figure><img src="/assets/characters/thumbs/${s.kind}-${s.id}.png"><figcaption>${s.label}</figcaption></figure>`).join('')}</div>`).join('')}<footer>Rendered from the exported Blender geometry. Hair and skin colours remain customisable in the live 3D wardrobe.</footer>`;
writeFileSync(root+'/catalog.html',html);
const server=await createServer({configFile:false,root:process.cwd(),server:{host:'127.0.0.1',port:0}});let browser;
try{await server.listen();browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1320,height:1000}});await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/${root}/catalog.html`);await page.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(img=>img.decode())));await page.screenshot({path:root+'/catalog.png',fullPage:true});}finally{await browser?.close();await server.close();}
