import {test,expect} from '@playwright/test';
// @ts-ignore
import {createBasketball} from '../server/basketball.mjs';
test('one ball owner, timed shot, authoritative points and rebound',()=>{
 let time=10000;const sent:any[]=[];const game=createBasketball((ws:any,m:any)=>sent.push({ws,...m}),()=>time);const a={id:'a',name:'Ali',ws:'a',x:54,z:129},b={id:'b',name:'Bala',ws:'b',x:54,z:129};const ps=new Map([['a',a],['b',b]]);const send=(p:any,type:string)=>game.handle(ps,p,{type});const state=()=>sent.filter(m=>m.type==='basketball-state').at(-1).game;
 send(a,'basketball-grab');send(b,'basketball-grab');expect(state().holder).toBe('a');send(b,'basketball-shoot');expect(state().holder).toBe('a');send(a,'basketball-charge');time+=800;send(a,'basketball-shoot');expect(state().shooting).toBe(true);
 time+=1200;game.tick(ps);game.tick(ps);expect(state().scores[0].points).toBe(3);time+=500;for(let i=0;i<10;i++)game.tick(ps);expect(state().scores[0].points).toBe(3);expect(state().shooting).toBe(false);
 send(b,'basketball-grab');expect(state().holder).toBeNull();b.z=state().ball.z;b.x=state().ball.x;send(b,'basketball-grab');expect(state().holder).toBe('b');b.z=0;game.tick(ps);for(let i=0;i<10;i++)game.tick(ps);expect(state().holder).toBeNull();
});
test('mistimed distance shot misses and riding player cannot collect',()=>{
 let time=10000;const sent:any[]=[];const game=createBasketball((ws:any,m:any)=>sent.push(m),()=>time);const p={id:'a',name:'A',ws:'a',x:54,z:129,riding:true};const ps=new Map([['a',p]]);game.handle(ps,p,{type:'basketball-grab'});expect(sent.length).toBe(0);p.riding=false;game.handle(ps,p,{type:'basketball-grab'});game.handle(ps,p,{type:'basketball-shoot'});time+=1700;for(let i=0;i<12;i++)game.tick(ps);expect(sent.at(-1).game.scores).toEqual([]);expect(sent.at(-1).game.shooting).toBe(false);
});
test('court placement, basketball controls and mobile charge release',async({page})=>{
 await page.goto('/');await page.evaluate(async()=>{
 const THREE=await import('/node_modules/three/build/three.module.js');const {createWorld}=await import('/src/world.ts');const {createBasketball}=await import('/src/basketball.ts');document.body.innerHTML='';const scene=new THREE.Scene();scene.background=new THREE.Color('#b4cdbb');const world=createWorld(scene);(window as any).overlaps=world.solids.filter(s=>Math.abs(s.x-54)<s.hx+8&&Math.abs(s.z-129)<s.hz+13);const game=createBasketball(scene,world);(window as any).sent=[];game.connect(m=>{(window as any).sent.push(m);return true;});game.state({holder:'a',ball:{x:54,y:1,z:129},shooting:false,scores:[],notice:'Tahan Shoot'});game.update({x:54,z:129},true,.1,true,'a');scene.add(new THREE.HemisphereLight(0xffffff,0x608070,3));const camera=new THREE.PerspectiveCamera(48,900/700,.1,500);camera.position.set(73,25,152);camera.lookAt(54,0,129);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(900,700);document.body.append(renderer.domElement);renderer.render(scene,camera);
 });expect(await page.evaluate(()=>(window as any).overlaps)).toEqual([]);await page.screenshot({path:'/tmp/basketball-court.png'});
 await page.setViewportSize({width:375,height:812});await page.locator('canvas').evaluate(el=>el.style.display='none');const button=page.getByRole('button',{name:'Tahan untuk Shoot'});await expect(button).toBeEnabled();const b=await button.boundingBox();expect(b!.x).toBeGreaterThanOrEqual(0);expect(b!.x+b!.width).toBeLessThanOrEqual(375);await button.dispatchEvent('pointerdown',{pointerId:1});await button.dispatchEvent('pointerup',{pointerId:1});expect(await page.evaluate(()=>(window as any).sent.map((m:any)=>m.type))).toEqual(['basketball-charge','basketball-shoot']);
});
