import { test, expect } from '@playwright/test';
import type { Page } from '@playwright/test';
interface GameState { stick: { x: number; y: number }; seated: boolean; profileScreen: { x: number; y: number }; punchCount: number; jumpHeight: number; started: boolean; paused: boolean; riding: boolean; position: { x: number; z: number }; speed: number; money: number; simTime: number; rain: boolean; drawCalls: number }
const state = (page: Page) => page.evaluate(() => (window as unknown as { __lepak: GameState }).__lepak);

test('free roam supports riding, settings and no mission prompts', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.locator('#loading')).toBeHidden();
  await page.screenshot({ path: 'test-results/title-screen.png' });
  await page.getByRole('button', { name: "Jom, let's go" }).click();
  await page.locator('#world').click({ position: { x: 640, y: 400 } });
  expect((await state(page)).punchCount).toBe(1);
  await page.mouse.move(640, 400); await page.mouse.down(); await page.mouse.move(680, 400); await page.mouse.up();
  expect((await state(page)).punchCount).toBe(1);
  await page.keyboard.press('c');
  const profilePoint = (await state(page)).profileScreen;
  await page.mouse.click(profilePoint.x, profilePoint.y, { button: 'right' });
  await page.getByRole('menuitem', { name: 'View profile' }).click();
  await expect(page.locator('#profile-name')).not.toBeEmpty();
  await page.keyboard.press('Escape');
  await expect(page.locator('#player-profile')).not.toBeVisible();
  await page.keyboard.press('m');
  await expect(page.getByRole('dialog', { name: 'Know your streets.' })).toBeVisible();
  const mapPosition = (await state(page)).position.x;
  await page.keyboard.down('d');
  await expect.poll(async () => (await state(page)).position.x).toBeGreaterThan(mapPosition + .5);
  await page.keyboard.up('d');
  const mapTime = (await state(page)).simTime;
  await expect.poll(async () => (await state(page)).simTime).toBeGreaterThan(mapTime);
  await page.screenshot({ path: 'test-results/expanded-map-desktop.png' });
  await page.keyboard.press('m');
  await expect(page.locator('#city-map')).not.toBeVisible();
  await page.keyboard.press('m');
  await page.keyboard.press('Escape');
  await expect(page.locator('#city-map')).not.toBeVisible();
  await expect(page.locator('#pause')).toBeHidden();
  await page.keyboard.down('Space');
  await expect.poll(async () => (await state(page)).jumpHeight, { intervals: [30] }).toBeGreaterThan(.4);
  await expect.poll(async () => (await state(page)).jumpHeight).toBe(0);
  await page.waitForTimeout(300);
  expect((await state(page)).jumpHeight).toBe(0);
  await page.keyboard.up('Space');
  await expect(page.locator('#mission-card')).toHaveCount(0);
  await expect(page.locator('#interaction')).toBeHidden();
  await page.keyboard.press('Enter');
  await expect(page.locator('#interaction')).toBeHidden();
  await page.keyboard.down('d');
  await expect.poll(async () => (await state(page)).position.x, { timeout: 15000 }).toBeGreaterThan(-9.6);
  await page.keyboard.up('d');
  await page.keyboard.press('e');
  expect((await state(page)).riding).toBe(false);
  await page.keyboard.press('Enter');
  await expect.poll(async () => (await state(page)).riding).toBe(true);
  await page.keyboard.down('w');
  await expect.poll(async () => (await state(page)).position.z, { timeout: 45000 }).toBeLessThan(-82);
  await page.keyboard.up('w');
  await page.keyboard.down('Space');
  await expect.poll(async () => Math.abs((await state(page)).speed)).toBeLessThan(.4);
  await page.keyboard.up('Space');
  await page.keyboard.press('Enter');
  await expect.poll(async () => (await state(page)).riding).toBe(false);
  await page.keyboard.down('d');
  await expect.poll(async () => (await state(page)).position.x, { timeout: 12000 }).toBeGreaterThan(-2.2);
  await page.keyboard.up('d');
  // Adjust a possible frame/poll overshoot through normal walking input.
  const current = await state(page);
  if (current.position.z < -88) {
    await page.keyboard.down('s');
    await expect.poll(async () => (await state(page)).position.z).toBeGreaterThan(-87);
    await page.keyboard.up('s');
  }
  await expect(page.locator('#money')).toHaveText('RM 0');
  await page.keyboard.press('Escape');
  const pausedAt = (await state(page)).simTime;
  await page.getByLabel('Rain over KL').check();
  await page.keyboard.press('w');
  await expect.poll(async () => (await state(page)).simTime).toBeGreaterThan(pausedAt);
  expect((await state(page)).rain).toBe(true);
  await page.getByRole('button', { name: 'Back to the streets' }).click();
  await expect.poll(async () => (await state(page)).paused).toBe(false);
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  await expect(page.locator('#pause')).toBeHidden();
  await expect.poll(async () => page.locator('#background-music').evaluate((audio: HTMLAudioElement) => audio.paused)).toBe(false);
  await page.reload();
  await expect(page.locator('#loading')).toBeHidden();
  await page.getByRole('button', { name: "Jom, let's go" }).click();
  await expect(page.locator('#money')).toHaveText('RM 0');
  expect(errors).toEqual([]);
});

test('mobile layout exposes usable touch controls and pause recovery', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const page = await context.newPage();
  await page.goto('/');
  await expect(page.locator('#loading')).toBeHidden();
  await page.getByRole('button', { name: "Jom, let's go" }).click();
  await expect(page.locator('#touch-controls')).toBeVisible();
  await page.touchscreen.tap(195, 420);
  expect((await state(page)).punchCount).toBe(1);
  const touchProfile = (await state(page)).profileScreen;
  const cdp = await context.newCDPSession(page);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [touchProfile] });
  await page.waitForTimeout(600);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await page.getByRole('menuitem', { name: 'View profile' }).tap();
  await expect(page.locator('#profile-name')).not.toBeEmpty();
  await page.getByRole('button', { name: 'Close', exact: true }).tap();
  expect((await state(page)).punchCount).toBe(1);
  await page.getByRole('button', { name: 'Open city map' }).tap();
  await expect(page.locator('#city-map')).toBeVisible();
  const mapBounds = await page.locator('#city-map').boundingBox();
  expect(mapBounds!.x).toBeGreaterThanOrEqual(0);
  expect(mapBounds!.x + mapBounds!.width).toBeLessThanOrEqual(390);
  await page.screenshot({ path: 'test-results/expanded-map-mobile.png' });
  await page.getByRole('button', { name: 'Close city map' }).tap();
  await expect(page.locator('#city-map')).not.toBeVisible();
  await page.getByRole('button', { name: 'Jump', exact: true }).tap();
  await expect.poll(async () => (await state(page)).jumpHeight, { intervals: [30] }).toBeGreaterThan(.3);
  await expect.poll(async () => (await state(page)).jumpHeight).toBe(0);
  await expect(page.getByRole('button', { name: 'Spam recall emote' })).toBeVisible();
  await page.getByRole('button', { name: 'Spam recall emote' }).click();
  await expect(page.locator('#toast')).toContainText('BZZ BZZ BZZ BZZ');
  await expect(page.locator('#mission-card')).toHaveCount(0);
  await page.getByRole('button', { name: 'Open settings' }).click();
  await page.getByRole('button', { name: 'Return to Mamak Maju' }).click();
  await expect(page.locator('#pause')).toBeHidden();
  expect((await state(page)).money).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/mobile-game.png' });
  await context.close();
});

test('Enter sits at a nearby chair and stands without opening chat', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: "Jom, let's go" }).click();
  await page.keyboard.down('a');
  await expect.poll(async () => (await state(page)).position.x).toBeLessThan(-26);
  await page.keyboard.up('a');
  await page.keyboard.press('Enter');
  await expect.poll(async () => (await state(page)).seated).toBe(true);
  const sitting = (await state(page)).position;
  await page.keyboard.press('w');
  expect((await state(page)).position).toEqual(sitting);
  await expect(page.locator('#chat-input')).not.toBeFocused();
  await page.keyboard.press('Enter');
  await expect.poll(async () => (await state(page)).seated).toBe(false);
});

test('mobile analog movement supports release and a second finger in both orientations', async ({ browser }) => {
  for (const viewport of [{ width: 360, height: 780 }, { width: 844, height: 390 }]) {
    const context = await browser.newContext({ viewport, isMobile: true, hasTouch: true });
    const page = await context.newPage();
    await page.goto('/');
    await page.getByRole('button', { name: "Jom, let's go" }).click();
    await expect(page.locator('.touch-pad')).toHaveCount(0);
    await page.getByRole('button', { name: 'Open city map' }).tap();
    await expect(page.locator('#city-map')).toBeVisible();
    const rect = (await page.locator('#move-stick').boundingBox())!;
    const cdp = await context.newCDPSession(page);
    const point = { x: rect.x + rect.width / 2 + 25, y: rect.y + rect.height / 2, id: 1 };
    const before = (await state(page)).position.x;
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [point] });
    await expect.poll(async () => (await state(page)).position.x).toBeGreaterThan(before + .3);
    const strength = (await state(page)).stick.x;
    expect(strength).toBeGreaterThan(.4); expect(strength).toBeLessThan(.9);
    const cameraPoint = { x: viewport.width / 2, y: viewport.height / 2, id: 2 };
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [point, cameraPoint] });
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [point, { ...cameraPoint, x: cameraPoint.x + 30 }] });
    expect((await state(page)).stick.x).toBeCloseTo(strength);
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    expect((await state(page)).stick).toEqual({ x: 0, y: 0 });
    expect((await state(page)).punchCount).toBe(0);
    const stopped = (await state(page)).position;
    await page.waitForTimeout(150);
    expect((await state(page)).position).toEqual(stopped);
    await page.screenshot({ path: `test-results/analog-${viewport.width}.png` });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await context.close();
  }
});
