import {test,expect} from '@playwright/test';
import {createLukis,wordHint} from '../server/lukis.mjs';
import chairs from '../shared/chairs.json' with {type:'json'};
function fixture(count=3,onSend?:(ws:string,message:any)=>void){let time=100000;const events:any[]=[];const seats=chairs.filter(c=>c.tableId==='meja-1');const ps=new Map(Array.from({length:count},(_,i)=>[String(i),{id:String(i),userId:`account-${i}`,name:`Player ${i}`,chairId:seats[i].id,ws:String(i)}]));const engine=createLukis((ws:string,m:any)=>{events.push({ws,...structuredClone(m)});onSend?.(ws,m);},()=>time,(n:number)=>n-1);const state=(i=0)=>events.filter(e=>e.ws===String(i)&&e.type==='lukis-state').at(-1).game;const send=(i:number,m:any)=>engine.handle(ps,ps.get(String(i)),m);const act=(i:number,type:string,extra:any={})=>{const s=state(i);send(i,{type,gameId:s.id,round:s.round,boardVersion:s.boardVersion,...extra});};return{ps,events,engine,state,send,act,step(ms:number){time+=ms;engine.tick(ps);}};}
test('private word selection, aliases, ranking, timed hints and complete match',()=>{
 const f=fixture();f.send(0,{type:'lukis-start',version:2});expect(f.state().phase).toBe('choosing');expect(f.state().choices).toHaveLength(3);expect(f.state(1).choices).toEqual([]);expect(f.state(1).word).toBe('');f.act(1,'lukis-choose',{choice:0});expect(f.state().phase).toBe('choosing');f.act(0,'lukis-choose',{choice:0});expect(f.state().word).toBe('lampu isyarat');f.act(1,'lukis-guess',{text:'traffic lights'});expect(f.state(1).scores.find((p:any)=>p.id==='account-1').score).toBe(500);f.step(10000);f.act(2,'lukis-guess',{text:'lampu isyarat'});expect(f.state(2).roundWinners[1]).toMatchObject({points:415,timeBonus:250,placeBonus:65,artistPoints:138});expect(f.state().phase).toBe('reveal');const points=f.state(1).scores.find((p:any)=>p.id==='account-1').score;f.act(1,'lukis-guess',{text:'traffic lights'});expect(f.state(1).scores.find((p:any)=>p.id==='account-1').score).toBe(points);
 f.step(6000);expect(f.state().drawer).toBe('account-1');f.step(12000);expect(f.state().phase).toBe('drawing');f.step(20000);const first=f.state(0).word;f.step(20000);const second=f.state(0).word;[...first].forEach((c,i)=>{if(/[A-Z]/.test(c))expect(second[i]).toBe(c);});f.step(20000);f.step(6000);expect(f.state().drawer).toBe('account-2');f.step(12000);f.step(60000);f.step(6000);expect(f.state().phase).toBe('finished');expect(f.state().round).toBe(3);
 expect(wordHint('telefon',2)).toContain('T');
});
test('ink batches, undo/redo, undo clear and stale epoch rejection',()=>{
 const f=fixture(2);f.send(0,{type:'lukis-start',version:2});f.act(0,'lukis-choose',{choice:0});const line=(id:number,color='#20382e')=>[.1,.5,.9,.5,color,7,id];f.act(1,'lukis-ink',{seq:1,lines:[line(1)]});f.act(0,'lukis-ink',{seq:1,lines:[line(1)]});f.act(0,'lukis-ink',{seq:2,lines:[line(2,'#ffffff')]});f.send(0,{type:'lukis-open'});expect(f.state().lines).toHaveLength(2);const old={...f.state()};f.act(0,'lukis-undo');expect(f.state().lines).toHaveLength(1);f.act(0,'lukis-redo');expect(f.state().lines).toHaveLength(2);f.act(0,'lukis-clear');expect(f.state().lines).toEqual([]);f.act(0,'lukis-undo');expect(f.state().lines).toHaveLength(2);f.send(0,{type:'lukis-ink',gameId:old.id,round:old.round,boardVersion:old.boardVersion,seq:3,lines:[line(3)]});expect(f.state().lines).toHaveLength(2);f.act(0,'lukis-undo');f.act(0,'lukis-ink',{seq:4,lines:[line(4)]});f.send(0,{type:'lukis-open'});expect(f.state().canRedo).toBe(false);expect(f.state().lines.map((l:any)=>l[6])).toEqual([1,4]);
});
test('reconnection by account preserves drawing role and turn score',()=>{const f=fixture(3);f.send(0,{type:'lukis-start',version:2});f.act(0,'lukis-choose',{choice:0});const old=f.ps.get('0')!;f.ps.set('0',{...old,id:'replacement'});f.send(0,{type:'lukis-open'});expect(f.state().self).toBe('account-0');expect(f.state().drawer).toBe('account-0');f.act(0,'lukis-ink',{seq:1,lines:[[.1,.1,.2,.2,'#20382e',7,1]]});f.send(0,{type:'lukis-open'});expect(f.state().lines).toHaveLength(1);});
test('two-player disconnect gets a grace period, then cancels if nobody returns',()=>{const f=fixture(2);f.send(0,{type:'lukis-start',version:2});f.act(0,'lukis-choose',{choice:0});const player=f.ps.get('1')!;f.ps.delete('1');f.step(1000);expect(f.state().waitingForPlayers).toBe(true);f.step(10000);f.ps.set('1',{...player,id:'reconnected'});f.step(1000);expect(f.state().waitingForPlayers).toBe(false);expect(f.state().phase).toBe('drawing');f.ps.delete('1');f.step(1000);f.step(30000);expect(f.state()).toBeNull();});

test('two browsers draw, erase, undo, redo, clear and hear a correct answer',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const pages=[await context.newPage(),await context.newPage()];const deliveries:Promise<any>[]=[];const errors:string[]=[];
 const f=fixture(2,(ws,m)=>{deliveries.push(pages[Number(ws)].evaluate((message:any)=>{const ui=(window as any).ui;if(message.type==='lukis-state')ui.state(message.game,'unused');else if(message.type==='lukis-ink')ui.ink(message);else if(message.type==='lukis-correct')ui.correct(message.name,message.points,message);else if(message.type==='lukis-feedback')ui.feedback(message.kind,message.message);},structuredClone(m)));});
 for(const [i,page] of pages.entries()){page.on('pageerror',e=>errors.push(e.message));await page.route('**/lukis-test.html',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><body style="margin:0"></body>'}));await page.goto('http://127.0.0.1:5173/lukis-test.html');await page.exposeFunction('gameSend',(m:any)=>f.send(i,m));await page.evaluate(async()=>{const Base=window.AudioContext;(window as any).tones=0;window.AudioContext=class extends Base{createOscillator(){(window as any).tones++;return super.createOscillator();}};const{setupLukis}=await import('/src/lukis.ts');const ui=setupLukis(m=>{void(window as any).gameSend(m);return true;});(window as any).ui=ui;document.body.append(ui.root);});}
 const flush=async()=>{while(deliveries.length)await Promise.all(deliveries.splice(0));};
 await pages[0].getByRole('button',{name:'Mula permainan',exact:true}).click();await expect(pages[0].locator('.lukis-choices button')).toHaveCount(3);await pages[0].locator('.lukis-choices button').first().click();await expect(pages[0].getByText('Lukis: lampu isyarat')).toBeVisible();await flush();
 const canvas=pages[0].locator('canvas');const box=await canvas.boundingBox();const stroke=async(from:number,to:number)=>{await pages[0].mouse.move(box!.x+box!.width*from,box!.y+box!.height*.5);await pages[0].mouse.down();await pages[0].mouse.move(box!.x+box!.width*to,box!.y+box!.height*.5,{steps:18});await pages[0].mouse.up();await flush();};const alpha=(page:any,x=.5)=>page.locator('canvas').evaluate((el:HTMLCanvasElement,x:number)=>el.getContext('2d')!.getImageData(Math.round(el.width*x),el.height/2,1,1).data[3],x);
 await stroke(.1,.9);await expect.poll(()=>alpha(pages[1])).toBe(255);await expect(pages[0].getByRole('button',{name:'Undo stroke'})).toBeEnabled();await pages[0].getByRole('button',{name:'⌫ Pemadam',exact:true}).click();await pages[0].getByRole('button',{name:'Saiz berus 24',exact:true}).click();await stroke(.35,.65);await expect.poll(()=>alpha(pages[1])).toBe(0);await pages[0].getByRole('button',{name:'Undo stroke'}).click();await expect.poll(()=>alpha(pages[1])).toBe(255);await pages[0].getByRole('button',{name:'Redo stroke'}).click();await expect.poll(()=>alpha(pages[1])).toBe(0);
 await pages[0].getByRole('button',{name:'Padam semua',exact:true}).click();await pages[0].getByRole('button',{name:'Ya, padam',exact:true}).click();await expect.poll(()=>alpha(pages[1],.2)).toBe(0);await pages[0].getByRole('button',{name:'Undo stroke'}).click();await expect.poll(()=>alpha(pages[1],.2)).toBe(255);
 await pages[0].getByRole('button',{name:'✎ Berus',exact:true}).click();await pages[0].touchscreen.tap(box!.x+box!.width*.5,box!.y+box!.height*.5);await expect.poll(()=>alpha(pages[1])).toBe(255);await flush();await flush();const metric=(p:any)=>p.locator('canvas').evaluate((c:HTMLCanvasElement)=>{const a=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data;let sum=0,count=0,hash=0;for(let i=0;i<a.length;i++){sum+=a[i];if(a[i])count++;hash=(Math.imul(hash,31)+a[i])>>>0;}return {sum,count,hash};});await expect.poll(async()=>JSON.stringify(await metric(pages[0]))===JSON.stringify(await metric(pages[1]))).toBe(true);
 await pages[1].getByLabel('Jawapan Lukis Lah').fill('traffic light');await pages[1].getByRole('button',{name:'Teka!',exact:true}).click();await expect(pages[1].locator('.lukis-feedback')).toContainText('betul');await expect(pages[0].locator('.lukis-results')).toContainText('500');await expect.poll(()=>pages[1].evaluate(()=>(window as any).tones)).toBe(3);expect(errors).toEqual([]);await context.close();
});
