import {test,expect} from '@playwright/test';
import {createUno,unoDeck,unoPlayable,unoPoints} from '../server/uno.mjs';
import chairs from '../shared/chairs.json' with {type:'json'};
function fixture(seed=123,count=3){let t=100000,random=seed;const events:any[]=[];const seats=chairs.filter(c=>c.tableId==='meja-1');const ps=new Map<string,any>(Array.from({length:count},(_,i)=>[String(i),{id:String(i),userId:`u${i}`,name:`P${i}`,chairId:seats[i].id,ws:String(i)}]));const engine=createUno((ws:any,m:any)=>events.push({ws,...structuredClone(m)}),()=>t,(n:number)=>{random=(Math.imul(random,1664525)+1013904223)>>>0;return random%n;});const state=(i=0)=>events.filter(e=>e.ws===String(i)).at(-1)?.game;const send=(i:number,m:any)=>engine.handle(ps,ps.get(String(i)),m);const act=(i:number,type:string,extra:any={})=>{const g=state(i);send(i,{type,gameId:g.id,revision:g.revision,...extra});};for(let i=0;i<count;i++)send(i,{type:'uno-join'});send(0,{type:'uno-start'});const step=(ms:number)=>{t+=ms;engine.tick(ps);};step(3200);return {ps,engine,events,state,send,act,step,count};}
function playStep(f:ReturnType<typeof fixture>,call=true){const g=f.state(),i=Number(g.turn.slice(1)),s=f.state(i),card=s.hand.find((c:any)=>s.playable.includes(c.id)&&c.color!=='wild')||s.hand.find((c:any)=>s.playable.includes(c.id));if(card)f.act(i,'uno-play',{cardId:card.id,color:'red',uno:call});else f.act(i,s.drawn?'uno-pass':'uno-draw');}
function suitable(value:string,count=3){for(let seed=1;seed<300;seed++){const f=fixture(seed,count),g=f.state(0),card=g.hand.find((c:any)=>c.value===value&&g.playable.includes(c.id));if(card)return {f,card};}throw Error('No fixture');}
test('108 unique cards, valid matching, Draw Four restriction and points',()=>{const deck=unoDeck();expect(deck).toHaveLength(108);expect(new Set(deck.map(c=>c.id)).size).toBe(108);const red=deck.find(c=>c.color==='red'&&c.value==='1')!,blue=deck.find(c=>c.color==='blue'&&c.value==='2')!,wild=deck.find(c=>c.value==='draw4')!;expect(unoPlayable(wild,blue,'red',[red,wild])).toBe(false);expect(unoPlayable(wild,blue,'blue',[red,wild])).toBe(true);expect(unoPlayable(red,blue,'blue',[red])).toBe(false);expect(unoPoints(wild)).toBe(50);expect(unoPoints(red)).toBe(1);expect(unoPoints(deck.find(c=>c.value==='skip')!)).toBe(20);});
test('deals seven private cards, protects turn and rejects replayed actions',()=>{const f=fixture();expect(f.state().hand).toHaveLength(7);expect(f.state().players.every((p:any)=>!('hand'in p))).toBe(true);expect(/^\d$/.test(f.state().top.value)).toBe(true);const before=f.state(1).hand;f.act(1,'uno-play',{cardId:before[0].id,color:'red'});expect(f.state(1).hand).toEqual(before);const old=f.state();playStep(f);const revision=f.state().revision;f.send(0,{type:'uno-draw',gameId:old.id,revision:old.revision});expect(f.state().revision).toBe(revision);
 const watcher={id:'watch',name:'Watcher',chairId:seatsForWatcher(),ws:'watch'};f.ps.set('watch',watcher);f.engine.handle(f.ps,watcher,{type:'uno-open'});expect(f.events.at(-1).game.hand).toEqual([]);
});
function seatsForWatcher(){return chairs.find(c=>c.tableId==='meja-1')!.id;}
test('skip, two-player reverse and draw penalties skip the next turn',()=>{for(const value of ['skip','reverse','draw2']){const {f,card}=suitable(value,2);f.act(0,'uno-play',{cardId:card.id});expect(f.state().turn).toBe('u0');expect(f.state(1).hand.length).toBe(value==='draw2'?9:7);}});
test('wild colour requires valid selection and is applied by server',()=>{const {f,card}=suitable('wild');const before=f.state().revision;f.act(0,'uno-play',{cardId:card.id,color:'purple'});expect(f.state().revision).toBe(before);f.act(0,'uno-play',{cardId:card.id,color:'blue'});expect(f.state().color).toBe('blue');expect(f.state().top.id).toBe(card.id);});
test('UNO catch awards two cards once, and full rounds score correctly',()=>{const f=fixture(26);let caught=false;for(let i=0;i<900&&f.state().phase==='playing';i++){playStep(f,false);const g=f.state();if(g.unoTarget&&!caught){const target=Number(g.unoTarget.slice(1)),other=(target+1)%3;expect(f.state(target).hand).toHaveLength(1);f.act(other,'uno-catch');expect(f.state(target).hand).toHaveLength(3);f.act(other,'uno-catch');expect(f.state(target).hand).toHaveLength(3);caught=true;}}expect(caught).toBe(true);const g=f.state();expect(g.phase).toBe('round-over');expect(g.winner).toBeTruthy();const points=[0,1,2].filter(i=>`u${i}`!==g.winner).reduce((sum,i)=>sum+f.state(i).hand.reduce((n:number,c:any)=>n+unoPoints(c),0),0);expect(g.roundPoints).toBe(points);f.send(0,{type:'uno-start'});expect(f.state().phase).toBe('dealing');expect(f.state().round).toBe(2);expect(f.state().players.find((p:any)=>p.id===g.winner).score).toBe(points);});
test('timeout advances, reconnect restores hand and absence forfeits',()=>{const f=fixture(11,2),hand=f.state(0).hand;const p=f.ps.get('0');f.ps.delete('0');f.step(1000);f.ps.set('0',{...p,id:'new-id'});f.send(0,{type:'uno-open'});expect(f.state(0).hand).toEqual(hand);f.step(25000);expect(f.state().turn).toBe('u1');f.ps.delete('1');f.step(1000);f.step(60000);expect(f.state().phase).toBe('round-over');expect(f.state().winner).toBe('u0');});
test('an exhausted deck ends a blocked round without losing or duplicating cards',()=>{const f=fixture();for(let n=0;n<250&&f.state().phase==='playing';n++){const i=Number(f.state().turn.slice(1)),s=f.state(i);f.act(i,s.drawn?'uno-pass':'uno-draw');}expect(f.state().phase).toBe('round-over');expect(f.state().winner).toBeNull();const all=[f.state().top,...[0,1,2].flatMap(i=>f.state(i).hand)];expect(all).toHaveLength(108);expect(new Set(all.map(c=>c.id)).size).toBe(108);});
test('mobile cards, wild picker, dealing and game-menu entry',async({page})=>{
 const f=suitable('wild');await page.setViewportSize({width:390,height:844});await page.goto('/');await page.waitForTimeout(300);await page.evaluate(async state=>{document.querySelectorAll('#table-social').forEach(e=>e.remove());const {setupTableSocial}=await import('/src/table-social.ts');const sent:any[]=[];(window as any).unoSent=sent;const ui=setupTableSocial(m=>{sent.push(m);return true;},'test',()=>{},()=>{});ui.state([{id:'meja-1',name:'Meja 1',capacity:3,occupants:[{id:'0',name:'P0',chairId:'chair-0'}]}],'0',true);ui.uno(state);ui.open('meja-1');},f.f.state());const d=page.locator('#table-social[open]');await d.locator('[data-select="uno"]').click();await expect(d.locator('.uno')).toBeVisible();await expect(d.locator('.poker')).toBeHidden();await d.locator(`.uno-hand [data-card="${f.card.id}"]`).click();await expect(d.locator('.uno-picker')).toBeVisible();await d.locator('.uno-picker [data-color="blue"]').click();expect(await page.evaluate(()=>(window as any).unoSent.at(-1))).toMatchObject({type:'uno-play',color:'blue'});expect(await d.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);await d.getByRole('button',{name:'Mute card sounds'}).click();await expect(d.getByRole('button',{name:'Enable card sounds'})).toBeVisible();
});
