import {test,expect} from '@playwright/test';
import {createWerewolf,WEREWOLF_TIMES} from '../server/werewolf.mjs';
import chairs from '../shared/chairs.json' with {type:'json'};
function fixture(size=7){let time=100000;const events:any[]=[];const ps=new Map<string,any>(Array.from({length:size},(_,i)=>[String(i),{id:String(i),userId:`user-${i}`,name:`Player ${i}`,chairId:chairs[i].id,ws:String(i)}]));const engine=createWerewolf((ws:any,m:any)=>events.push({ws,...structuredClone(m)}),()=>time,(n:number)=>n-1);const p=(i:number)=>ps.get(String(i));const state=(i:number)=>events.filter(e=>e.ws===String(i)&&e.type==='werewolf-state').at(-1).game;const send=(i:number,m:any)=>engine.handle(ps,p(i),m);send(0,{type:'werewolf-join'});if(size!==7)send(0,{type:'werewolf-size',size});for(let i=1;i<size;i++)send(i,{type:'werewolf-join'});send(0,{type:'werewolf-start'});return{ps,events,engine,p,state,send,act(i:number,target:string){const s=state(i);send(i,{type:'werewolf-action',gameId:s.id,revision:s.revision,target});},step(ms:number){time+=ms;engine.tick(ps);}};}
test('secret cards, spectator privacy, doctor protection and seer results',()=>{
 const f=fixture();expect(f.state(0).role).toBe('werewolf');expect(f.state(4).players.filter((p:any)=>p.role!==null)).toHaveLength(1);expect(f.state(0).players.filter((p:any)=>p.role==='werewolf')).toHaveLength(2);
 f.ps.set('spectator',{id:'spectator',name:'Watcher',chairId:chairs[8].id,ws:'spectator'});f.engine.handle(f.ps,f.ps.get('spectator'),{type:'werewolf-open'});expect(f.events.at(-1).game.players.every((p:any)=>p.role===null)).toBe(true);
 f.send(0,{type:'werewolf-chat',text:'secret wolf plan'});expect(JSON.stringify(f.state(4))).not.toContain('secret wolf plan');expect(JSON.stringify(f.state(1))).toContain('secret wolf plan');
 f.act(0,'user-4');f.act(1,'user-4');f.act(2,'user-4');f.act(3,'user-0');f.step(WEREWOLF_TIMES.night);expect(f.state(4).players.every((p:any)=>p.alive)).toBe(true);expect(f.state(3).inspection.team).toBe('evil');expect(f.state(4).inspection).toBeNull();expect(f.state(0).phase).toBe('discussion');
});
test('full accusation, defense, judgment, stale actions and good victory',()=>{
 const f=fixture();f.step(WEREWOLF_TIMES.night);f.step(WEREWOLF_TIMES.discussion);f.act(4,'user-0');f.act(5,'user-0');f.act(6,'user-0');f.step(WEREWOLF_TIMES.vote);expect(f.state(4).phase).toBe('defense');expect(f.state(4).accused).toBe('user-0');const old=f.state(4).revision;
 f.step(WEREWOLF_TIMES.defense);f.send(4,{type:'werewolf-action',gameId:f.state(4).id,revision:old,target:'kill'});expect(f.state(4).selected).toBeNull();f.act(1,'kill');expect(f.state(1).selected).toBeNull();f.act(4,'kill');f.act(5,'kill');f.step(WEREWOLF_TIMES.judgment);expect(f.state(4).players.find((p:any)=>p.id==='user-0').alive).toBe(false);expect(f.state(4).phase).toBe('night');
 f.act(0,'user-4');expect(f.state(0).selected).toBeNull();f.step(WEREWOLF_TIMES.night);f.step(WEREWOLF_TIMES.discussion);f.act(4,'user-1');f.act(5,'user-1');f.step(WEREWOLF_TIMES.vote);f.step(WEREWOLF_TIMES.defense);f.act(4,'kill');f.act(5,'kill');f.step(WEREWOLF_TIMES.judgment);expect(f.state(4).winner).toBe('good');expect(f.state(4).players.every((p:any)=>p.role)).toBe(true);
});
test('nine players, Alpha camouflage and disconnected-player grace',()=>{
 const f=fixture(9);expect(f.state(2).role).toBe('alpha');f.act(4,'user-2');f.step(WEREWOLF_TIMES.night);expect(f.state(4).inspection.team).toBe('good');f.ps.delete('0');f.step(1000);expect(f.state(3).players.find((p:any)=>p.id==='user-0').alive).toBe(true);f.step(60000);expect(f.state(3).players.find((p:any)=>p.id==='user-0').alive).toBe(false);
});
test('ties skip trial, evil parity ends game and host can create a fresh lobby',()=>{
 const f=fixture();f.step(WEREWOLF_TIMES.night);f.step(WEREWOLF_TIMES.discussion);f.act(4,'user-0');f.act(5,'user-1');f.step(WEREWOLF_TIMES.vote);expect(f.state(4).phase).toBe('night');for(const i of [4,5,6])f.send(i,{type:'werewolf-leave'});expect(f.state(0).winner).toBe('evil');const old=f.state(0).id;f.send(1,{type:'werewolf-rematch'});expect(f.state(0).id).toBe(old);f.send(0,{type:'werewolf-rematch'});expect(f.state(0).phase).toBe('lobby');expect(f.state(0).id).not.toBe(old);expect(f.state(0).players).toEqual([]);
});
test('rejoining by account restores role and ghosts cannot leak messages into live chat',()=>{
 const f=fixture();const original=f.p(4);f.ps.delete('4');f.step(1000);const reconnected={...original,id:'new-4'};f.ps.set('4',reconnected);f.step(1000);f.send(4,{type:'werewolf-open'});expect(f.state(4).role).toBe('villager');expect(f.state(4).players.find((p:any)=>p.id==='user-4').alive).toBe(true);f.send(4,{type:'werewolf-leave'});f.send(4,{type:'werewolf-chat',text:'ghost only secret'});expect(JSON.stringify(f.state(0))).not.toContain('ghost only secret');expect(JSON.stringify(f.state(4))).toContain('ghost only secret');f.send(0,{type:'werewolf-chat',text:'wolf only secret'});expect(JSON.stringify(f.state(4))).not.toContain('wolf only secret');
});
test('mobile Werewolf card opens and untrusted names remain plain text',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.waitForTimeout(300);await page.evaluate(async()=>{document.querySelectorAll('#table-social').forEach(e=>e.remove());const{setupTableSocial}=await import('/src/table-social.ts');const ui=(window as any).ui=setupTableSocial(()=>true,'test',()=>{},()=>{});ui.state([{id:'meja-1',name:'Meja 1',capacity:3,occupants:[{id:'a',name:'A',chairId:'chair-0'}]}],'a',true);ui.werewolf({id:'test',phase:'lobby',revision:0,day:0,ends:0,serverTime:Date.now(),size:7,host:'a',self:'a',players:[{id:'a',name:'<img src=x>',alive:true,online:true,role:null}],role:null,log:[],chat:[]});ui.open('meja-1');});
 const dialog=page.locator('#table-social[open]');await dialog.locator('[data-select="werewolf"]').click();await page.evaluate(g=>(window as any).ui?.lobby({key:'meja-1',game:g,scope:g==='werewolf'?'city':'table',phase:'playing',ends:0,serverTime:0,min:2,max:9,members:[{id:'self',name:'You',ready:true},{id:'p2',name:'Kawan',ready:true}]}),'werewolf');await expect(dialog.locator('.werewolf')).toBeVisible();await expect(dialog.locator('.lukis')).toBeHidden();await expect(dialog.locator('.werewolf img')).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Mula permainan'})).toBeDisabled();expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
});
