import chairs from '../shared/chairs.json' with {type:'json'};
import {randomInt} from 'node:crypto';
const words=['nasi lemak','teh tarik','roti canai','durian','kucing','payung','basikal','kereta','KLCC','bola sepak','pisang goreng','ikan','rumah kampung','pokok kelapa','ais krim','cermin mata','selipar','kopi','bunga raya','telefon','motosikal','mamak','masjid','wau bulan','satay','kompang','harimau','beca','ketupat','baju melayu'];
const colors=['#20382e','#e34b4b','#327bd1','#2caa68','#e9b52c','#9b59b6','#f08bb4','#8b5a2b','#ffffff'],sizes=[3,7,14,24];
const tableOf=p=>chairs.find(c=>c.id===p.chairId)?.tableId;
const normal=s=>String(s).toLocaleLowerCase('ms-MY').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const closeGuess=(guess,word)=>{const a=normal(guess),b=normal(word);if(!a||Math.abs(a.length-b.length)>1)return false;let edits=0,i=0,j=0;while(i<a.length&&j<b.length){if(a[i]===b[j]){i++;j++;continue;}if(++edits>1)return false;if(a.length>b.length)i++;else if(b.length>a.length)j++;else{i++;j++;}}return edits+Math.abs((a.length-i)-(b.length-j))<=1;};
const hint=(word,stage)=>{let letters=0;return[...word].map((c,index)=>{if(c===' ')return '  ';if(stage===0)return '_';if(stage===1)return index===0||word[index-1]===' '?c.toUpperCase():'_';letters++;return letters%3===1?c.toUpperCase():'_';}).join(' ');};
export function scoreGuess(remainingSeconds,place){return 100+Math.max(0,Math.min(300,Math.ceil(remainingSeconds)*5))+Math.max(0,100-(place-1)*35);}
export function createLukis(send,now=Date.now){
 const games=new WeakMap(),members=(ps,id)=>[...ps.values()].filter(p=>tableOf(p)===id);
 function publicState(g,p){const drawing=g.phase==='drawing',drawer=p.id===g.drawer,remaining=Math.max(0,Math.ceil((g.ends-now())/1000)),stage=remaining<=20?2:remaining<=40?1:0;return{tableId:g.tableId,phase:g.phase,drawer:g.drawer,round:g.round,total:g.order.length,ends:g.ends,word:drawing&&!drawer?hint(g.word,stage):g.word,scores:g.order.map(id=>({id,name:g.names[id],score:g.scores[id]||0,roundPoints:g.roundPoints[id]||0})).sort((a,b)=>b.score-a.score),lines:g.lines,solved:g.solved,roundWinners:g.roundWinners};}
 function state(ps,g){for(const p of members(ps,g.tableId))send(p.ws,{type:'lukis-state',game:publicState(g,p)});}
 function next(g){g.round++;g.lines=[];g.strokes=[];g.solved=[];g.roundWinners=[];g.roundPoints=Object.fromEntries(g.order.map(id=>[id,0]));g.lastHintStage=0;g.lastLine=0;g.lineWindow=0;g.lineCount=0;if(g.round>g.order.length){g.phase='finished';g.ends=0;return;}g.drawer=g.order[g.round-1];g.word=words[randomInt(words.length)];g.phase='drawing';g.ends=now()+60000;}
 function tick(ps){const map=games.get(ps);if(!map)return;for(const [id,g] of map){const people=members(ps,id);if(people.length<2){map.delete(id);for(const p of people)send(p.ws,{type:'lukis-state',game:null});continue;}if(g.phase==='drawing'){const remaining=g.ends-now(),stage=remaining<=20000?2:remaining<=40000?1:0;if(stage!==g.lastHintStage){g.lastHintStage=stage;state(ps,g);}if(remaining<=0||!people.some(p=>p.id===g.drawer)){g.phase='reveal';g.ends=now()+5000;state(ps,g);}}else if(g.phase==='reveal'&&now()>=g.ends){next(g);state(ps,g);}}}
 return{tick,handle(ps,p,m){if(!['lukis-open','lukis-start','lukis-line','lukis-undo','lukis-clear','lukis-guess'].includes(m.type))return false;tick(ps);const id=tableOf(p);if(!id){send(p.ws,{type:'notice',message:'Duduk semeja dahulu untuk Lukis Lah!'});return true;}if(!games.has(ps))games.set(ps,new Map());const map=games.get(ps);let g=map.get(id);const people=members(ps,id);
  if(m.type==='lukis-start'){if(people.length<2){send(p.ws,{type:'notice',message:'Ajak sekurang-kurangnya seorang lagi duduk semeja.'});return true;}if(g&&g.phase!=='finished')return true;g={tableId:id,order:people.map(q=>q.id),names:Object.fromEntries(people.map(q=>[q.id,q.name])),scores:Object.fromEntries(people.map(q=>[q.id,0])),roundPoints:{},roundWinners:[],round:0,lines:[],strokes:[],solved:[],word:'',phase:'',ends:0};map.set(id,g);next(g);state(ps,g);return true;}
  if(m.type==='lukis-open'){if(g)state(ps,g);else send(p.ws,{type:'lukis-state',game:null});return true;}if(!g||g.phase!=='drawing')return true;
  if(m.type==='lukis-line'&&g.drawer===p.id){if(g.lines.length>=6000)return true;if(now()-g.lineWindow>=1000){g.lineWindow=now();g.lineCount=0;}if(g.lineCount>=160)return true;let a=m.line;if(Array.isArray(a)&&a.length===6)a=[...a,0];if(!Array.isArray(a)||a.length!==7||!a.slice(0,4).every(n=>Number.isFinite(n)&&n>=0&&n<=1)||!colors.includes(a[4])||!sizes.includes(a[5])||!Number.isSafeInteger(a[6])||a[6]<0||a[6]>1e9)return true;g.lastLine=now();g.lineCount++;g.lines.push(a);if(g.strokes.at(-1)!==a[6])g.strokes.push(a[6]);for(const q of people)send(q.ws,{type:'lukis-line',line:a});return true;}
  if(m.type==='lukis-undo'&&g.drawer===p.id&&now()-(g.lastUndo||0)>250){g.lastUndo=now();const stroke=g.strokes.pop();if(stroke!==undefined){g.lines=g.lines.filter(line=>line[6]!==stroke);state(ps,g);}return true;}
  if(m.type==='lukis-clear'&&g.drawer===p.id&&now()-(g.lastClear||0)>700){g.lastClear=now();g.lines=[];g.strokes=[];state(ps,g);return true;}
  if(m.type==='lukis-guess'&&p.id!==g.drawer&&g.order.includes(p.id)&&!g.solved.includes(p.id)&&typeof m.text==='string'&&m.text.length<=60){if(now()-(p.lukisGuessAt||0)<500)return true;p.lukisGuessAt=now();const near=closeGuess(m.text,g.word);if(normal(m.text)===normal(g.word)){const place=g.solved.length+1,points=scoreGuess((g.ends-now())/1000,place),artistPoints=40;g.solved.push(p.id);g.scores[p.id]=(g.scores[p.id]||0)+points;g.scores[g.drawer]=(g.scores[g.drawer]||0)+artistPoints;g.roundPoints[p.id]=points;g.roundPoints[g.drawer]=(g.roundPoints[g.drawer]||0)+artistPoints;g.roundWinners.push({id:p.id,name:p.name,points,place});for(const q of people)send(q.ws,{type:'lukis-correct',id:p.id,name:p.name,points,place});if(g.solved.length>=g.order.filter(playerId=>playerId!==g.drawer&&people.some(q=>q.id===playerId)).length){g.phase='reveal';g.ends=now()+5000;}state(ps,g);}else send(p.ws,{type:'lukis-feedback',kind:near?'close':'wrong',message:near?'Hampir tepat! 🔥':'Belum tepat. Cuba lagi!'});return true;}
  return true;}};
}
