import { randomInt, randomUUID } from 'node:crypto';
import chairs from '../shared/chairs.json' with {type:'json'};
import {filterChat} from './chat-filter.mjs';

const key=p=>p.userId||p.id;
const seated=p=>chairs.some(c=>c.id===p.chairId);
const evil=role=>role==='werewolf'||role==='alpha';
export const WEREWOLF_TIMES={night:35000,discussion:60000,vote:25000,defense:20000,judgment:20000};
export function createWerewolf(send,now=Date.now,pick=randomInt){
 const rooms=new WeakMap();
 const fresh=()=>({id:randomUUID(),phase:'lobby',revision:0,day:0,ends:0,size:7,host:null,players:[],actions:{},votes:{},judgments:{},accused:null,accusers:[],log:[],chat:[],winner:null});
 function room(ps){if(!rooms.has(ps))rooms.set(ps,fresh());return rooms.get(ps);}
 const alive=g=>g.players.filter(p=>p.alive);
 const entry=(g,id)=>g.players.find(p=>p.id===id);
 function log(g,text){g.log.push(text);g.log=g.log.slice(-30);}
 function phase(g,value){g.phase=value;g.revision++;g.ends=now()+(WEREWOLF_TIMES[value]||0);g.actions={};if(value==='night'){g.day++;g.votes={};g.judgments={};g.accused=null;g.accusers=[];}if(value==='vote')g.votes={};if(value==='judgment')g.judgments={};}
 function finish(g){const living=alive(g),wolves=living.filter(p=>evil(p.role));if(!wolves.length||wolves.length>=living.length-wolves.length){g.winner=!wolves.length?'good':'evil';phase(g,'finished');log(g,g.winner==='good'?'Penduduk menang! Semua serigala telah disingkirkan.':'Serigala menang! Kampung telah dikuasai.');return true;}return false;}
 function eliminate(g,p,reason){if(!p?.alive)return;p.alive=false;log(g,`${p.name} tersingkir (${reason}). Peranan: ${p.role}.`);}
 function view(g,id){const me=entry(g,id),isWolf=me?.alive&&evil(me.role),finished=g.phase==='finished';return{id:g.id,phase:g.phase,revision:g.revision,day:g.day,ends:g.ends,serverTime:now(),size:g.size,host:g.host,self:id,winner:g.winner,accused:g.accused,players:g.players.map(p=>({id:p.id,name:p.name,alive:p.alive,online:!p.missingAt,role:finished||p.id===id||!p.alive||p.revealed||(isWolf&&evil(p.role))?p.role:null})),role:me?.role||null,inspection:me?.inspection||null,selected:g.phase==='night'?g.actions[id]||null:g.phase==='vote'?g.votes[id]||null:g.judgments[id]||null,canJudge:g.accusers.includes(id)&&id!==g.accused&&!!me?.alive,log:g.log,chat:g.chat.filter(m=>m.channel==='day'||finished||m.channel==='wolves'&&isWolf||m.channel==='ghosts'&&me&&!me.alive).slice(-60)};}
 function publish(ps,g){for(const p of ps.values())if(seated(p))send(p.ws,{type:'werewolf-state',game:view(g,key(p))});}
 function resolveNight(g){const living=alive(g),wolves=living.filter(p=>evil(p.role)),choices=wolves.map(p=>g.actions[p.id]).filter(id=>living.some(p=>p.id===id&&!evil(p.role)));let victimId=choices.length?choices.every(id=>id===choices[0])?choices[0]:choices[pick(choices.length)]:null;const doctor=living.find(p=>p.role==='doctor'),seer=living.find(p=>p.role==='seer');if(seer){const target=entry(g,g.actions[seer.id]);if(target?.alive)seer.inspection={name:target.name,team:target.role==='werewolf'?'evil':'good',day:g.day};}
  const victim=entry(g,victimId);if(victim&&doctor&&g.actions[doctor.id]===victim.id){log(g,'Malam berlalu. Tiada sesiapa terkorban.');}else if(victim?.role==='knight'&&!victim.used){victim.used=true;log(g,'Malam berlalu. Tiada sesiapa terkorban.');}else if(victim){eliminate(g,victim,'malam');if(victim.role==='hunter'&&pick(4)<3){const targets=alive(g).filter(p=>evil(p.role));if(targets.length)eliminate(g,targets[pick(targets.length)],'Hunter');}}else log(g,'Malam berlalu. Tiada sesiapa terkorban.');if(!finish(g))phase(g,'discussion');
 }
 function advance(g){if(g.phase==='night')resolveNight(g);else if(g.phase==='discussion')phase(g,'vote');else if(g.phase==='vote'){const tally={};for(const p of alive(g)){const target=g.votes[p.id];if(target&&target!=='skip'&&entry(g,target)?.alive)tally[target]=(tally[target]||0)+(p.role==='mayor'?2:1);}const ranked=Object.entries(tally).sort((a,b)=>b[1]-a[1]);if(!ranked.length||ranked[1]?.[1]===ranked[0][1]){log(g,'Undian seri atau tiada tuduhan. Tiada hukuman hari ini.');phase(g,'night');}else{g.accused=ranked[0][0];g.accusers=alive(g).filter(p=>g.votes[p.id]===g.accused).map(p=>p.id);log(g,`${entry(g,g.accused).name} dituduh. Masa untuk membela diri.`);phase(g,'defense');}}else if(g.phase==='defense')phase(g,'judgment');else if(g.phase==='judgment'){const judges=g.accusers.filter(id=>entry(g,id)?.alive&&id!==g.accused),kill=judges.filter(id=>g.judgments[id]==='kill').length;const accused=entry(g,g.accused);if(accused?.alive&&kill>judges.length/2){if(accused.role==='princess'&&!accused.used){accused.used=true;accused.revealed=true;log(g,`${accused.name} ialah Princess dan terselamat sekali.`);}else eliminate(g,accused,'undian');}else log(g,`${accused?.name||'Tertuduh'} dibebaskan.`);if(!finish(g))phase(g,'night');}}
 function tick(ps){const g=rooms.get(ps);if(!g)return;const present=new Set([...ps.values()].filter(seated).map(key));let changed=false;for(const p of [...g.players]){if(present.has(p.id)){if(p.missingAt){p.missingAt=0;changed=true;}}else if(g.phase==='lobby'){g.players=g.players.filter(q=>q!==p);changed=true;}else if(g.phase!=='finished'&&p.alive){if(!p.missingAt){p.missingAt=now();changed=true;}if(now()-p.missingAt>=60000){eliminate(g,p,'meninggalkan permainan');changed=true;}}}if(!g.players.some(p=>p.id===g.host)){g.host=g.players[0]?.id||null;changed=true;}if(!['lobby','finished'].includes(g.phase)){if(finish(g))changed=true;else if(now()>=g.ends){advance(g);changed=true;}}if(changed)publish(ps,g);}
 return {tick,handle(ps,p,m){if(typeof m.type!=='string'||!m.type.startsWith('werewolf-'))return false;if(!seated(p)){send(p.ws,{type:'notice',message:'Duduk di mana-mana meja untuk Werewolf.'});return true;}tick(ps);let g=room(ps);const id=key(p),me=entry(g,id);const reply=()=>send(p.ws,{type:'werewolf-state',game:view(g,id)});
  if(m.type==='werewolf-open'){reply();return true;}
  if(m.type==='werewolf-join'&&g.phase==='lobby'){if(!me&&g.players.length<g.size){g.players.push({id,name:p.name,alive:true,role:null,used:false,missingAt:0});g.host??=id;publish(ps,g);}else reply();return true;}
  if(m.type==='werewolf-leave'&&me){if(g.phase==='lobby'){g.players=g.players.filter(q=>q!==me);if(g.host===id)g.host=g.players[0]?.id||null;}else if(g.phase!=='finished'&&me.alive){eliminate(g,me,'keluar');finish(g);}publish(ps,g);return true;}
  if(m.type==='werewolf-size'&&g.phase==='lobby'&&g.host===id&&[7,9].includes(m.size)&&g.players.length<=m.size){g.size=m.size;publish(ps,g);return true;}
  if(m.type==='werewolf-rematch'&&g.phase==='finished'&&(g.host===id||!presentHost(ps,g.host))){g=fresh();rooms.set(ps,g);publish(ps,g);return true;}
  if(m.type==='werewolf-start'&&g.phase==='lobby'&&g.host===id&&g.players.length===g.size){let roles=['werewolf','werewolf','doctor','seer','villager','villager','villager'];if(g.size===9){const extras=['knight','princess','hunter','mayor'];const first=extras.splice(pick(extras.length),1)[0],second=extras[pick(extras.length)];roles=['werewolf','werewolf','alpha','doctor','seer','villager','villager',first,second];}for(let i=roles.length-1;i>0;i--){const j=pick(i+1);[roles[i],roles[j]]=[roles[j],roles[i]];}g.players.forEach((q,i)=>q.role=roles[i]);log(g,'Peranan telah dibahagi. Rahsiakan kad anda.');phase(g,'night');publish(ps,g);return true;}
  if(m.type==='werewolf-chat'&&me&&typeof m.text==='string'&&m.text.length<=240){if(now()-(me.chatAt||0)<900)return true;let channel=g.phase==='lobby'||g.phase==='finished'?'day':!me.alive?'ghosts':g.phase==='night'&&evil(me.role)?'wolves':['discussion','vote','judgment'].includes(g.phase)||g.phase==='defense'&&g.accused===id?'day':null;if(channel){const text=filterChat(m.text.replace(/[\u0000-\u001f\u007f]/g,' ').trim());if(text){me.chatAt=now();g.chat.push({name:me.name,text,channel});g.chat=g.chat.slice(-120);publish(ps,g);}}return true;}
  if(!me?.alive||m.gameId!==g.id||m.revision!==g.revision)return true;
  if(m.type==='werewolf-action'){const target=entry(g,m.target);if(g.phase==='night'&&target?.alive&&(evil(me.role)&&!evil(target.role)||me.role==='doctor'||me.role==='seer'&&target.id!==id)){g.actions[id]=target.id;reply();}else if(g.phase==='vote'&&(m.target==='skip'||target?.alive&&target.id!==id)){g.votes[id]=m.target;reply();}else if(g.phase==='judgment'&&g.accusers.includes(id)&&g.accused!==id&&['kill','spare'].includes(m.target)){g.judgments[id]=m.target;reply();}}return true;}};
}
function presentHost(ps,id){return [...ps.values()].some(p=>key(p)===id&&seated(p));}
