import './lukis.css';
export function setupLukis(send:(m:object)=>boolean){
 const root=document.createElement('section');root.className='lukis';root.innerHTML=`<h3>🎨 Lukis Lah!</h3><p>Seorang lukis, geng teka. Duduk semeja dengan 2+ pemain.</p><details><summary>Cara kira mata</summary><p>100 mata untuk jawapan betul + sehingga 300 bonus masa. Peneka pertama dapat 100 bonus, kedua 65. Pelukis dapat 40 setiap jawapan betul. Setiap pemain mendapat satu giliran melukis. Petunjuk muncul selepas 20 dan 40 saat.</p></details><button type="button" class="lukis-start">Mula / Main lagi</button><button type="button" class="lukis-open">Lihat permainan</button><div class="lukis-play" hidden><strong class="lukis-word"></strong><p class="lukis-time"></p><canvas width="640" height="400" aria-label="Papan Lukis Lah"></canvas><div class="lukis-tools"></div><form><input maxlength="60" placeholder="Teka perkataan…" aria-label="Jawapan Lukis Lah" required><button>Teka!</button></form><p class="lukis-score"></p></div>`;
 const canvas=root.querySelector('canvas')!,ctx=canvas.getContext('2d')!,form=root.querySelector('form')!,tools=root.querySelector<HTMLElement>('.lukis-tools')!;
 let game:any=null,self='',color='#20382e',size=7,prev:number[]|null=null,pointer:number|null=null,last=0,stroke=0;
 const drawing=()=>game?.phase==='drawing'&&game.drawer===self;
 function line(a:any){ctx.globalCompositeOperation=a[4]==='#ffffff'?'destination-out':'source-over';ctx.strokeStyle=a[4];ctx.lineWidth=a[5];ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a[0]*640,a[1]*400);ctx.lineTo(a[2]*640,a[3]*400);ctx.stroke();if(a[0]===a[2]&&a[1]===a[3]){ctx.fillStyle=a[4];ctx.beginPath();ctx.arc(a[0]*640,a[1]*400,a[5]/2,0,Math.PI*2);ctx.fill();}ctx.globalCompositeOperation='source-over';}
 function paint(){ctx.clearRect(0,0,640,400);ctx.fillStyle='#ffffff';ctx.fillRect(0,0,640,400);for(const a of game?.lines||[])line(a);}
 function render(){root.querySelector<HTMLElement>('.lukis-play')!.hidden=!game;root.querySelector<HTMLButtonElement>('.lukis-start')!.disabled=!!game&&game.phase!=='finished';if(!game)return;root.querySelector<HTMLElement>('.lukis-word')!.textContent=game.phase==='finished'?`🏆 ${[...game.scores].sort((a:any,b:any)=>b.score-a.score)[0]?.name||'Geng'} · Tamat! Jom satu lagi?`:`${drawing()?'Lukis: ':game.phase==='reveal'?'Jawapan: ':'Teka: '}${game.word}`;tools.hidden=!drawing();form.hidden=!game||game.phase!=='drawing'||drawing()||game.solved.includes(self);canvas.style.touchAction=drawing()?'none':'auto';const scoreboard=root.querySelector<HTMLElement>('.lukis-score')!;scoreboard.replaceChildren();[...game.scores].sort((a:any,b:any)=>b.score-a.score).forEach((s:any,index:number)=>{const row=document.createElement('span');row.textContent=`${index+1}. ${s.name}${s.id===game.drawer?' ✏️':''} · ${s.score} mata${s.roundPoints?' (+'+s.roundPoints+')':''}`;scoreboard.append(row);});paint();}
 for(const c of ['#20382e','#e34b4b','#327bd1','#2caa68','#e9b52c','#ffffff']){const b=document.createElement('button');b.type='button';b.style.background=c;b.title=c==='#ffffff'?'Pemadam':c;b.setAttribute('aria-label',b.title);b.onclick=()=>{color=c;tools.querySelectorAll('button').forEach(el=>el.classList.remove('selected'));b.classList.add('selected');};tools.append(b);}
 for(const n of [3,7,14,24]){const b=document.createElement('button');b.type='button';b.textContent=String(n);b.onclick=()=>{size=n;tools.querySelectorAll('[data-size]').forEach(el=>el.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');};b.dataset.size=String(n);b.setAttribute('aria-label',`Saiz berus ${n}`);b.setAttribute('aria-pressed',String(n===size));tools.append(b);}const clear=document.createElement('button');clear.type='button';clear.textContent='Padam semua';clear.onclick=()=>send({type:'lukis-clear'});tools.append(clear);const undo=document.createElement('button');undo.type='button';undo.textContent='↶ Undo';undo.onclick=()=>send({type:'lukis-undo'});tools.append(undo);
 root.querySelector<HTMLButtonElement>('.lukis-start')!.onclick=()=>send({type:'lukis-start'});root.querySelector<HTMLButtonElement>('.lukis-open')!.onclick=()=>send({type:'lukis-open'});
 form.onsubmit=e=>{e.preventDefault();const input=form.querySelector('input')!;send({type:'lukis-guess',text:input.value});input.value='';};
 const point=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect();return[Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];};
 canvas.onpointerdown=e=>{if(!drawing()||pointer!==null)return;e.preventDefault();pointer=e.pointerId;canvas.setPointerCapture(pointer);prev=point(e);last=0;stroke=(stroke+1)%1000000000;};
 canvas.onpointermove=e=>{if(!drawing()||pointer!==e.pointerId||!prev||performance.now()-last<25)return;e.preventDefault();last=performance.now();const p=point(e);const segment=[...prev,...p,color,size,stroke];if(send({type:'lukis-line',line:segment}))line(segment);prev=p;};
 const end=()=>{prev=null;pointer=null;};canvas.onpointerup=e=>{if(prev&&pointer===e.pointerId){const p=point(e);const segment=[...prev,...p,color,size,stroke];if(send({type:'lukis-line',line:segment}))line(segment);}end();};canvas.onpointercancel=end;canvas.onlostpointercapture=end;
 setInterval(()=>{if(game)root.querySelector<HTMLElement>('.lukis-time')!.textContent=`Giliran ${Math.min(game.round,game.total)}/${game.total} · ${game.phase==='finished'?'Selesai':Math.max(0,Math.ceil((game.ends-Date.now())/1000))+'s'}`;},250);
 const status=document.createElement('p');status.className='lukis-feedback';status.setAttribute('role','status');form.after(status);let audio:AudioContext|null=null;root.addEventListener('pointerdown',()=>{try{audio??=new (window.AudioContext||(window as any).webkitAudioContext)();void audio.resume();}catch{}});
 return {root,feedback(_kind:string,message:string){status.textContent=message;},correct(name:string,points:number){status.textContent=`✓ ${name} betul! +${points} mata`;if(audio?.state==='running'){[523,659,784].forEach((f,i)=>{const o=audio!.createOscillator(),g=audio!.createGain(),at=audio!.currentTime+i*.1;o.frequency.value=f;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.07,at+.02);g.gain.exponentialRampToValueAtTime(.0001,at+.22);o.connect(g).connect(audio!.destination);o.start(at);o.stop(at+.24);});}},state(value:any,id:string){const changed=game?.round!==value?.round||game?.phase!==value?.phase;game=value;self=id;if(changed){stroke=Math.max(stroke,...(value?.lines||[]).map((a:any)=>a[6]||0));}if(changed)end();render();},line(a:any){if(game){game.lines.push(a);if(!drawing())line(a);}}};
}
