import {auth,session,guestName} from './auth';
import fields from '../shared/profile-fields.json';
import './profile-social.css';
import './profile-social-overrides.css';
export type PlayerProfile = {id:string;name:string;registered:boolean;gameMaster?:boolean;details:Record<string,string>|null;stats?:{sessions:number;recalls:number;dances:number;basketballPoints:number};achievements?:{id:string;name:string;detail:string;unlockedAt:string}[];guestbook?:{id:string;authorId:string;author:string;text:string;createdAt:string}[];activity?:{type:string;label:string;createdAt:string}[];posts?:{id:string;text:string;mediaType:string|null;createdAt:string}[]};
const base=(import.meta.env.VITE_MULTIPLAYER_URL||'').replace(/^ws/i,'http').replace(/\/ws\/?$/,'').replace(/\/$/,'');
const when=(value:string)=>new Intl.DateTimeFormat('en-MY',{dateStyle:'medium',timeZone:'Asia/Kuala_Lumpur'}).format(new Date(value));
export function renderProfile(container:HTMLElement, profile:PlayerProfile) {
 container.replaceChildren();
 if(!profile.registered){const empty=document.createElement('p');empty.className='profile-empty';empty.textContent='Guest profile · Sign in to build a social profile.';container.append(empty);return;}
 const hero=document.createElement('header');hero.className='profile-hero';const cover=document.createElement('div');cover.className='profile-cover';cover.setAttribute('aria-hidden','true');const avatar=document.createElement('span');avatar.className='profile-avatar';avatar.textContent=profile.name.slice(0,1).toUpperCase();const intro=document.createElement('div');intro.className='profile-identity';const badge=document.createElement('p');badge.className='profile-badge';badge.textContent=profile.gameMaster?'✦ Game Master':'Kaki Lepak';const name=document.createElement('h3');name.textContent=profile.name;const resident=document.createElement('p');resident.className='profile-resident';resident.textContent=`Resident · ${profile.id.slice(-6).toUpperCase()}`;intro.append(badge,name,resident);hero.append(cover,avatar,intro);container.append(hero);
 let count=0;
 const list=document.createElement('dl');list.className='profile-about';
 for(const {key,label} of fields){const value=profile.details?.[key];if(!value)continue;const term=document.createElement('dt');term.textContent=label;const detail=document.createElement('dd');detail.textContent=value;list.append(term,detail);count++;}
 if(count)container.append(list);else{const empty=document.createElement('p');empty.className='profile-empty';empty.textContent='Still writing their story. Say hello!';container.append(empty);}
 if(profile.stats){const stats=document.createElement('section');stats.className='profile-stats';stats.setAttribute('aria-label','Player statistics');for(const [label,value,icon] of [['Visits',profile.stats.sessions,'◎'],['Recalls',profile.stats.recalls,'↻'],['Dances',profile.stats.dances,'♪'],['Basket points',profile.stats.basketballPoints,'●']] as const){const item=document.createElement('div'),symbol=document.createElement('span'),strong=document.createElement('strong'),small=document.createElement('small');symbol.textContent=icon;strong.textContent=String(value);small.textContent=String(label);item.append(symbol,strong,small);stats.append(item);}container.append(stats);}
 const badgeSection=document.createElement('section');badgeSection.className='profile-section';badgeSection.innerHTML=`<div class="profile-section-heading"><span>Collection</span><h4>Achievements</h4><b>${profile.achievements?.length||0}</b></div>`;const badges=document.createElement('div');badges.className='profile-achievements';for(const item of profile.achievements||[]){const card=document.createElement('article');const icon=document.createElement('span');icon.textContent=({first_lepak:'✦',regular:'☕',recall_rider:'↻',dance_floor:'♪',street_fighter:'★',table_regular:'▦',hoops:'●'} as Record<string,string>)[item.id]||'✦';const text=document.createElement('div'),title=document.createElement('strong'),detail=document.createElement('small');title.textContent=item.name;detail.textContent=item.detail;text.append(title,detail);card.append(icon,text);badges.append(card);}if(!badges.children.length){const empty=document.createElement('p');empty.className='profile-empty profile-empty-achievements';empty.textContent='Your badge shelf is waiting. Explore the city, play games and meet people to unlock your first achievement.';badges.append(empty);}badgeSection.append(badges);container.append(badgeSection);
 const activitySection=document.createElement('section');activitySection.className='profile-section';activitySection.innerHTML='<div class="profile-section-heading"><span>Timeline</span><h4>Recent activity</h4></div>';const activity=document.createElement('ol');activity.className='profile-activity';for(const item of profile.activity||[]){const li=document.createElement('li'),text=document.createElement('span'),time=document.createElement('time');text.textContent=item.label;time.dateTime=item.createdAt;time.textContent=when(item.createdAt);li.append(text,time);activity.append(li);}for(const item of profile.posts||[]){const li=document.createElement('li'),text=document.createElement('span'),time=document.createElement('time');text.textContent=item.text?`Posted: ${item.text.slice(0,80)}`:`Shared a ${item.mediaType||'moment'} on the Wall`;time.dateTime=item.createdAt;time.textContent=when(item.createdAt);li.append(text,time);activity.append(li);}if(!activity.children.length){const empty=document.createElement('p');empty.className='profile-empty';empty.textContent='No recent activity yet.';activitySection.append(empty);}else activitySection.append(activity);container.append(activitySection);
 const guestSection=document.createElement('section');guestSection.className='profile-section profile-guestbook';const head=document.createElement('div'),heading=document.createElement('h4'),countLabel=document.createElement('span');heading.textContent='Guestbook';countLabel.textContent=String(profile.guestbook?.length||0);head.append(heading,countLabel);guestSection.append(head);const entries=document.createElement('div');entries.className='profile-guestbook-list';function appendEntry(entry:NonNullable<PlayerProfile['guestbook']>[number],first=false){const article=document.createElement('article'),meta=document.createElement('div'),author=document.createElement('strong'),time=document.createElement('time'),body=document.createElement('p');author.textContent=entry.author;time.dateTime=entry.createdAt;time.textContent=when(entry.createdAt);body.textContent=entry.text;meta.append(author,time);if(session&&!guestName&&(entry.authorId===session.user.id||profile.id===session.user.id)){const remove=document.createElement('button');remove.type='button';remove.className='profile-guestbook-remove';remove.textContent='Remove';remove.setAttribute('aria-label',`Remove message from ${entry.author}`);remove.onclick=async()=>{remove.disabled=true;try{const response=await fetch(`${base}/profiles/${profile.id}/guestbook/${entry.id}`,{method:'DELETE',headers:{Authorization:`Bearer ${session!.access_token}`}});if(!response.ok){const data=await response.json();throw Error(data.error);}article.remove();countLabel.textContent=String(Math.max(0,Number(countLabel.textContent||0)-1));if(!entries.children.length){const empty=document.createElement('p');empty.className='profile-empty';empty.textContent='Be the first to leave a message.';entries.append(empty);}}catch(error){remove.disabled=false;remove.textContent=error instanceof Error?error.message:'Could not remove';}};meta.append(remove);}article.append(meta,body);if(first)entries.prepend(article);else entries.append(article);}for(const entry of profile.guestbook||[])appendEntry(entry);if(!entries.children.length){const empty=document.createElement('p');empty.className='profile-empty';empty.textContent='Be the first to leave a message.';entries.append(empty);}guestSection.append(entries);
 if(session&&!guestName){const form=document.createElement('form'),input=document.createElement('input'),button=document.createElement('button'),status=document.createElement('small');input.maxLength=160;input.placeholder=profile.id===session.user.id?'Leave a note on your profile…':'Say something nice…';button.type='submit';button.textContent='Write';status.setAttribute('role','status');form.append(input,button,status);form.onsubmit=async event=>{event.preventDefault();const text=input.value.trim();if(!text||!base)return;button.disabled=input.disabled=true;status.textContent='Posting…';try{const response=await fetch(`${base}/profiles/${profile.id}/guestbook`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session!.access_token}`},body:JSON.stringify({text})}),data=await response.json();if(!response.ok)throw Error(data.error);entries.querySelector('.profile-empty')?.remove();appendEntry(data.entry,true);input.value='';countLabel.textContent=String(Number(countLabel.textContent||0)+1);status.textContent='Message added.';}catch(error){status.textContent=error instanceof Error?error.message:'Could not post.';}finally{button.disabled=input.disabled=false;}};guestSection.append(form);}container.append(guestSection);
}
export function setupProfileEditor(onSave:(displayName:string)=>Promise<void>) {
 const dialog=document.createElement('dialog');dialog.id='edit-profile';dialog.setAttribute('aria-labelledby','edit-profile-title');
 dialog.innerHTML='<form><h2 id="edit-profile-title">Edit your profile</h2><p>Your display name appears above your character and in chat. The other details are optional and visible to players.</p><div id="profile-fields"></div><p id="profile-save-status" role="status"></p><div class="profile-editor-actions"><button type="submit">Save profile</button><button type="button">Cancel</button></div></form>';
 const form=dialog.querySelector('form')!, status=dialog.querySelector<HTMLElement>('[role=status]')!, save=form.querySelector<HTMLButtonElement>('[type=submit]')!, cancel=form.querySelector<HTMLButtonElement>('[type=button]')!, profileFields=dialog.querySelector<HTMLElement>('#profile-fields')!;
 const skeleton=document.createElement('div');skeleton.id='profile-editor-skeleton';skeleton.className='profile-editor-skeleton';skeleton.hidden=true;skeleton.setAttribute('aria-hidden','true');
 for(const large of [false,true,false,false,false,false,false]){const row=document.createElement('div');row.className='profile-skeleton-field';const label=document.createElement('span');label.className='profile-skeleton-label';const control=document.createElement('span');control.className=`profile-skeleton-control${large?' profile-skeleton-control-large':''}`;row.append(label,control);skeleton.append(row);}profileFields.after(skeleton);
 const inputs=new Map<string,HTMLInputElement|HTMLTextAreaElement>();
 const nameLabel=document.createElement('label');nameLabel.textContent='Display name';const nameInput=document.createElement('input');nameInput.id='profile-display-name';nameInput.name='displayName';nameInput.minLength=2;nameInput.maxLength=18;nameInput.required=true;nameInput.setAttribute('autocomplete','nickname');nameInput.placeholder='Your name in LepakMamak';nameLabel.htmlFor=nameInput.id;nameLabel.append(nameInput);profileFields.append(nameLabel);
 for(const field of fields){const label=document.createElement('label');label.textContent=field.label;const input=field.key==='bio'?document.createElement('textarea'):document.createElement('input');input.id=`profile-${field.key}`;input.name=field.key;input.maxLength=field.max;input.placeholder=field.placeholder;label.htmlFor=input.id;label.append(input);inputs.set(field.key,input);profileFields.append(label);}
 document.body.append(dialog);let busy=false,generation=0,loaded=false;
 function showLoading(value:boolean){profileFields.hidden=value;profileFields.setAttribute('aria-hidden',String(value));skeleton.hidden=!value;}
 function lock(value:boolean){busy=value;form.setAttribute('aria-busy',String(value));status.classList.toggle('profile-status-busy',value);save.disabled=cancel.disabled=value;save.textContent=value?(loaded?'Saving…':'Loading…'):'Save profile';nameInput.disabled=value;for(const input of inputs.values())input.disabled=value;if(value&&!loaded)showLoading(true);else if(!value)showLoading(false);}
 function close(){generation++;dialog.close();}
 cancel.onclick=close;dialog.addEventListener('cancel',event=>{if(busy)event.preventDefault();else generation++;});dialog.addEventListener('keydown',event=>event.stopPropagation());
 form.onsubmit=async event=>{
  event.preventDefault();if(busy||!loaded||!auth||!session||guestName)return;
  const id=session.user.id,attempt=generation;const displayName=nameInput.value.normalize('NFKC').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,18);
  if(displayName.length<2){nameInput.setCustomValidity('Enter at least two characters.');nameInput.reportValidity();return;}nameInput.setCustomValidity('');
  const profile=Object.fromEntries(fields.map(({key,max})=>[key,inputs.get(key)!.value.trim().slice(0,max)]));
  lock(true);status.textContent='Saving…';
  try{
   const {error}=await auth.auth.updateUser({data:{display_name:displayName,profile}});if(error)throw error;
   if(attempt!==generation)return;
   if(session?.user.id!==id||guestName)throw Error('Your session changed. Reopen your profile.');
   await onSave(displayName);close();
  }catch(error){if(attempt===generation)status.textContent=error instanceof Error?error.message:'Could not save. Please try again.';}
  finally{lock(false);}
 };
 return {close,async open(){
  if(!auth||!session||guestName)return;
  const id=session.user.id,attempt=++generation;loaded=false;status.textContent='Loading your profile…';showLoading(true);lock(true);if(!dialog.open)dialog.showModal();
  try{const {data,error}=await auth.auth.getUser();if(error)throw error;if(attempt!==generation)return;if(data.user?.id!==id||session?.user.id!==id||guestName)throw Error('Please log in again.');
   nameInput.value=String(data.user.user_metadata?.display_name||'').slice(0,18);
   for(const {key,max} of fields){const value=data.user.user_metadata?.profile?.[key];inputs.get(key)!.value=typeof value==='string'?value.slice(0,max):'';}
   loaded=true;status.textContent='';
  }catch(error){if(attempt===generation)status.textContent=error instanceof Error?error.message:'Could not load profile.';}
  finally{if(attempt===generation){lock(false);save.disabled=!loaded;nameInput.focus();}}
 }};
}
