import './uno.css';
import {createUnoAudio} from './uno-audio';
type Card={id:string;color:string;value:string};
type Player={id:string;name:string;count:number;score:number;left:boolean;online:boolean;uno:boolean};
type Game={id:string;tableId:string;revision:number;phase:string;round:number;host:string|null;self:string;turn:string|null;direction:number;color:string;top:Card|null;ends:number;serverTime:number;event:{id:number;type:string;text:string;who:string|null;count:number}|null;winner:string|null;roundPoints:number;target:number;breakdown:{id:string;name:string;points:number;cards:Card[]}[]|null;unoTarget:string|null;drawn:string|null;hand:Card[];players:Player[];playable:string[]};
const symbols:Record<string,string>={skip:'⊘',reverse:'⇄',draw2:'+2',wild:'✦',draw4:'+4'};
 const colorNames:Record<string,string>={red:'Red',yellow:'Yellow',green:'Green',blue:'Blue',wild:'Wild'};
const cardName=(c:Card)=>`${colorNames[c.color]||c.color} ${({skip:'Skip',reverse:'Reverse',draw2:'Draw Two',draw4:'Draw Four',wild:'Wild'} as Record<string,string>)[c.value]||c.value}`;
export function setupUno(send:(message:object)=>boolean){
 const root=document.createElement('section');root.className='uno';root.innerHTML=`<header class="uno-header"><div><small>MATCH COLOURS. PLAY TOGETHER.</small><h3>UNO<span>LEPAK</span></h3></div><button type="button" class="uno-sound" aria-label="Mute card sounds"></button></header><div class="uno-lobby"></div><div class="uno-meta"><strong></strong><time></time></div><div class="uno-opponents"></div><div class="uno-felt"><div class="uno-dealing" hidden><span class="uno-shuffle-card"></span><span class="uno-shuffle-card"></span><div class="uno-deal-flights"></div><strong>Shuffling… dealing cards!</strong></div><div class="uno-piles"><button type="button" class="uno-deck" aria-label="Draw a card"><span>LEPAK</span><small>DRAW CARD</small></button><div class="uno-discard" aria-label="Discard pile"></div></div><div class="uno-color"></div><div class="uno-winner" hidden></div></div><div class="uno-message" role="status" aria-live="polite"></div><div class="uno-breakdown" hidden></div><div class="uno-picker" hidden><strong>Choose the next colour</strong><div></div><button type="button" class="uno-cancel">Cancel</button></div><div class="uno-hand-heading"><strong>Your hand</strong><button type="button" class="uno-sort" aria-pressed="false">Sort</button><span></span></div><div class="uno-hand" aria-label="Your cards"></div><div class="uno-actions"><button type="button" class="uno-call" aria-pressed="false">UNO!</button><button type="button" class="uno-catch" hidden>Catch! +2</button><button type="button" class="uno-pass" hidden>Keep card · End turn</button></div><div class="uno-scores"></div><details class="uno-rules"><summary>How to play</summary><p>Join your friends at the table (minimum 2 players). The host starts when everyone is ready. Each player gets 7 cards. Match the colour, number or symbol. Wild cards let you choose the colour.</p><p>Skip skips the next player. Reverse changes direction (with two players it skips the opponent). +2 and +4 make the next player draw cards and lose their turn. Cards cannot be stacked. +4 is valid only when you have no card matching the current colour; the game checks this automatically.</p><p>Draw one card when you want to. If it is playable, play it or keep it and end your turn. Turns last 25 seconds; when time runs out, the game draws or ends the turn automatically.</p><p>Call UNO before playing your second-to-last card, or as soon as you have one card left. If you forget, an opponent can catch you before the next player acts: you draw 2 cards.</p><p>Empty your hand to win. The winner scores the value of every opponent&apos;s remaining cards: number cards use their face value, action cards are worth 20, and Wild cards are worth 50. Match targets are 200 points for two players, 300 for three, and 500 for four. There are no bets or purchases. If you stand up or disconnect for 60 seconds, you leave the round.</p></details>`;
 const el=<T extends HTMLElement>(s:string)=>root.querySelector<T>(s)!;
 const COLOUR_ORDER=['red','yellow','green','blue','wild'];
 const VALUE_ORDER=['0','1','2','3','4','5','6','7','8','9','skip','reverse','draw2','wild','draw4'];
 const byColour=(cards:Card[])=>[...cards].sort((a,b)=>COLOUR_ORDER.indexOf(a.color)-COLOUR_ORDER.indexOf(b.color)||VALUE_ORDER.indexOf(a.value)-VALUE_ORDER.indexOf(b.value));
 const audio=createUnoAudio();let sorted=false,game:Game|null=null,pending=false,armed=false,wildCard:Card|null=null,offset=0,lastEvent=0,lastGame='',previousTurn:string|null=null;
 const visible=()=>root.isConnected&&root.getClientRects().length>0;
 function soundLabel(){el('.uno-sound').textContent=audio.muted?'♪ Off':'♪ On';el('.uno-sound').setAttribute('aria-label',audio.muted?'Enable card sounds':'Mute card sounds');el('.uno-sound').setAttribute('aria-pressed',String(!audio.muted));}
 root.addEventListener('pointerdown',()=>audio.unlock());root.addEventListener('keydown',()=>audio.unlock());el('.uno-sound').onclick=()=>{audio.toggle();soundLabel();};soundLabel();
 function action(type:string,extra:object={}){if(!game||pending)return;audio.unlock();if(send({type,gameId:game.id,revision:game.revision,...extra})){pending=true;render();}}
 function button(text:string,fn:()=>void,disabled=false){const b=document.createElement('button');b.type='button';b.textContent=text;b.disabled=disabled;b.onclick=fn;return b;}
 function face(card:Card,interactive=false,back=false){const b=document.createElement(interactive?'button':'div');b.className=`uno-card ${back?'card-back':card.color}`;if(b instanceof HTMLButtonElement)b.type='button';b.setAttribute('aria-label',back?'Card back':cardName(card));if(back){b.textContent='LEPAK';return b;}const corner=document.createElement('small'),value=document.createElement('strong'),label=document.createElement('span');corner.textContent=symbols[card.value]||card.value;value.textContent=corner.textContent;label.textContent=colorNames[card.color];b.append(corner,value,label);return b;}
 function clock(){if(!game)return;el('time').textContent=game.ends?`${Math.max(0,Math.ceil((game.ends-Date.now()-offset)/1000))}s`:'';el('time').classList.toggle('urgent',game.phase==='playing'&&game.ends-Date.now()-offset<6000);}
 function render(){if(!game)return;const g=game,me=g.players.find(p=>p.id===g.self&&!p.left),myTurn=g.phase==='playing'&&g.turn===g.self&&!pending;root.dataset.phase=g.phase;const lobby=el('.uno-lobby');lobby.replaceChildren();if(['lobby','round-over'].includes(g.phase)){lobby.append(button(me?'Leave game':'Join UNO',()=>action(me?'uno-leave':'uno-join'),pending));if(g.host===g.self)lobby.append(button(g.phase==='round-over'?'Next round':'Shuffle & start',()=>action('uno-start'),pending||g.players.filter(p=>!p.left).length<2));}else if(g.phase==='finished'&&me)lobby.append(button('Back to Ready lobby',()=>action('uno-rematch'),pending));
  el('.uno-meta strong').textContent=g.phase==='lobby'?'Invite friends to sit at the table':g.phase==='dealing'?'Dealing 7 cards each':g.phase==='playing'?myTurn?'Your turn!':(g.players.find(p=>p.id===g.turn)?.name||'player')+"'s turn":g.phase==='finished'?'Match winner':'Round over';clock();
  const opponents=el('.uno-opponents');opponents.replaceChildren();for(const p of g.players.filter(p=>p.id!==g.self)){const seat=document.createElement('div'),name=document.createElement('strong'),count=document.createElement('span'),backs=document.createElement('div');seat.className='uno-opponent';seat.classList.toggle('active',p.id===g.turn);name.textContent=p.name;count.textContent=p.left?'Left':p.count+' cards'+(p.uno?' · UNO!':'')+(!p.online?' · Reconnecting…':'');backs.className='uno-backs';for(let i=0;i<Math.min(7,p.count);i++){const back=document.createElement('i');back.style.setProperty('--index',String(i));backs.append(back);}seat.append(name,backs,count);opponents.append(seat);}
  el('.uno-dealing').hidden=g.phase!=='dealing';const flights=el('.uno-deal-flights');flights.replaceChildren();if(g.phase==='dealing'){const elapsed=3200-Math.max(0,g.ends-Date.now()-offset),opponents=g.players.filter(p=>p.id!==g.self);for(let round=0;round<7;round++)g.players.forEach((p,index)=>{const card=document.createElement('i'),position=opponents.findIndex(q=>q.id===p.id);card.style.setProperty('--fly-x',p.id===g.self?'0px':String((position-(opponents.length-1)/2)*95)+'px');card.style.setProperty('--fly-y',p.id===g.self?'90px':'-90px');card.style.animationDelay=String(.65+(round*g.players.length+index)*.1-elapsed/1000)+'s';flights.append(card);});}el('.uno-piles').hidden=g.phase==='dealing'||g.phase==='lobby';el<HTMLButtonElement>('.uno-deck').disabled=!myTurn||!!g.drawn||!me;const discard=el('.uno-discard');discard.replaceChildren();if(g.top)discard.append(face(g.top));el('.uno-color').textContent=g.top?((g.direction===1?'↻':'↺')+' '+colorNames[g.color]+' · Round '+g.round):'';el('.uno-color').dataset.color=g.color;const winner=el('.uno-winner');winner.hidden=!['round-over','finished'].includes(g.phase);winner.textContent=g.winner?'🏆 '+(g.players.find(p=>p.id===g.winner)?.name||'Winner')+' +'+g.roundPoints+' points':'Round tied';
  el('.uno-message').textContent=g.event?.text||'Join to start playing.';el('.uno-hand-heading span').textContent=me?g.hand.length+' cards · '+me.score+'/'+g.target+' points':'Watching';const hand=el('.uno-hand'),scroll=hand.scrollLeft,focus=(document.activeElement as HTMLElement)?.dataset?.card;hand.replaceChildren();(sorted?byColour(g.hand):g.hand).forEach((c,index)=>{const b=face(c,true,g.phase==='dealing') as HTMLButtonElement;b.dataset.card=c.id;b.style.setProperty('--index',String(index));b.disabled=!myTurn||!g.playable.includes(c.id);b.classList.toggle('playable',!b.disabled);b.onclick=()=>{if(c.color==='wild'){wildCard=c;renderPicker();}else{wildCard=null;action('uno-play',{cardId:c.id,uno:armed});armed=false;}};hand.append(b);});hand.scrollLeft=scroll;if(focus){const target=Array.from(hand.querySelectorAll<HTMLButtonElement>('button')).find(b=>b.dataset.card===focus&&!b.disabled);target?.focus({preventScroll:true});}
  el<HTMLButtonElement>('.uno-call').disabled=pending||!me||g.phase!=='playing'||!(g.hand.length===2&&g.turn===g.self||g.unoTarget===g.self);el('.uno-call').setAttribute('aria-pressed',String(armed));el('.uno-call').textContent=armed?'✓ UNO armed':'UNO!';el('.uno-catch').hidden=!g.unoTarget||g.unoTarget===g.self||!me;el<HTMLButtonElement>('.uno-catch').disabled=pending;el('.uno-pass').hidden=!myTurn||!g.drawn;
  const bd=el('.uno-breakdown');bd.hidden=!g.breakdown?.length;bd.replaceChildren();for(const row of g.breakdown||[]){const line=document.createElement('div'),who=document.createElement('strong'),mini=document.createElement('div');who.textContent=row.name+' · '+row.points+' points';mini.className='uno-mini';for(const c of row.cards)mini.append(face(c));line.append(who,mini);bd.append(line);}const scores=el('.uno-scores');scores.replaceChildren();for(const p of [...g.players].sort((a,b)=>b.score-a.score)){const row=document.createElement('span');row.textContent=p.name+' · '+p.score+' points';scores.append(row);}renderPicker();
 }
 function renderPicker(){const picker=el('.uno-picker');picker.hidden=!wildCard||!game||game.turn!==game.self||game.phase!=='playing';if(!picker.hidden)el<HTMLButtonElement>('.uno-picker [data-color]')?.focus({preventScroll:true});}
 for(const color of ['red','yellow','green','blue']){const b=button(colorNames[color],()=>{if(!wildCard)return;const card=wildCard;wildCard=null;action('uno-play',{cardId:card.id,color,uno:armed});armed=false;});b.dataset.color=color;el('.uno-picker>div').append(b);}
 el('.uno-sort').onclick=()=>{sorted=!sorted;el('.uno-sort').setAttribute('aria-pressed',String(sorted));render();};el('.uno-cancel').onclick=()=>{wildCard=null;renderPicker();};el('.uno-deck').onclick=()=>action('uno-draw');el('.uno-pass').onclick=()=>action('uno-pass');el('.uno-catch').onclick=()=>action('uno-catch',{target:game?.unoTarget});el('.uno-call').onclick=()=>{if(game&&game.unoTarget===game.self)action('uno-call');else{armed=!armed;render();}};
 setInterval(()=>{if(visible())clock();},250);
 return{root,state(value:Game|null){pending=false;if(!value){game=null;wildCard=null;armed=false;lastGame='';lastEvent=0;return;}const changedGame=lastGame!==value.id,changedTurn=previousTurn!==value.turn;const newEvent=value.event&&value.event.id!==lastEvent;const hadState=!!game;const previousPhase=game?.phase,oldCards=new Set(game?.hand.map(c=>c.id)||[]);game=value;offset=value.serverTime-Date.now();if(changedGame||changedTurn||game.phase!=='playing'){armed=false;wildCard=null;}if(visible()&&newEvent&&hadState&&!changedGame){audio.sound(value.event!.type);if(changedTurn&&value.turn===value.self&&value.event!.type!=='deal')audio.sound('turn');}lastGame=value.id;lastEvent=value.event?.id||0;previousTurn=value.turn;render();if(visible()&&previousPhase==='dealing'&&value.phase==='playing')root.querySelectorAll('.uno-hand .uno-card').forEach((card,index)=>{if(!matchMedia('(prefers-reduced-motion: reduce)').matches)card.animate([{transform:'translateY(-50px) rotate(-12deg)',opacity:0},{transform:'translateY(0)',opacity:1}],{duration:320,delay:index*55,fill:'backwards'});});if(visible()&&newEvent&&hadState&&!changedGame&&previousPhase==='playing'&&value.phase==='playing'&&!matchMedia('(prefers-reduced-motion: reduce)').matches)root.querySelectorAll<HTMLElement>('.uno-hand [data-card]').forEach(card=>{if(!oldCards.has(card.dataset.card!))card.animate([{transform:'translateY(-40px) rotate(12deg)',opacity:0},{transform:'translateY(0)',opacity:1}],{duration:350});});if(visible()&&newEvent&&hadState&&value.event?.type==='play'&&!matchMedia('(prefers-reduced-motion: reduce)').matches)el('.uno-discard').animate([{transform:'translateY(-35px) rotate(15deg)',opacity:.3},{transform:'translateY(0) rotate(0)',opacity:1}],{duration:240});}};
}
