-- Handles, stored private messages and blocks for LepakMamak.
-- Written for the owner to apply before the realtime server deploys: without these tables
-- every send answers 503, the same hazard already recorded for the Wall.

-- One permanent, findable name per account. The server never updates a row: a handle that
-- could change would free the old one for impersonation.
create table if not exists public.player_handles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  handle text not null check (handle ~ '^[a-z0-9_]{3,18}$'),
  created_at timestamptz not null default now(),
  -- Also refused by the server; kept here so no other writer can claim them either.
  check (handle not in ('mod', 'moderator', 'gm', 'support', 'system')),
  check (handle !~ '^(admin|staff|official|lepakmamak)')
);

create unique index if not exists player_handles_handle_lower
  on public.player_handles (lower(handle));
-- Search is a prefix match; text_pattern_ops lets LIKE 'abc%' use the index whatever the collation.
create index if not exists player_handles_handle_prefix
  on public.player_handles (handle text_pattern_ops);

alter table public.player_handles enable row level security;
revoke all on table public.player_handles from public, anon, authenticated;
grant all on table public.player_handles to service_role;

-- Stored raw: a report needs the words actually sent, and censoring to *** destroys that.
-- The server filters on the way out.
create table if not exists public.game_messages (
  id uuid primary key default gen_random_uuid(),
  sender_user_id uuid not null references auth.users(id) on delete cascade,
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  -- Generated by the sender, reused on retry, so a lost response cannot store a message twice.
  client_id text not null check (char_length(client_id) between 1 and 64),
  sent_at timestamptz not null default now(),
  -- Unread is read_at is null; there is no counter to drift.
  read_at timestamptz,
  pair text generated always as (
    least(sender_user_id, recipient_user_id)::text || ':' || greatest(sender_user_id, recipient_user_id)::text
  ) stored,
  check (sender_user_id <> recipient_user_id),
  unique (sender_user_id, client_id)
);

create index if not exists game_messages_pair_sent
  on public.game_messages (pair, sent_at desc);
create index if not exists game_messages_recipient_unread
  on public.game_messages (recipient_user_id, read_at);

alter table public.game_messages enable row level security;
revoke all on table public.game_messages from public, anon, authenticated;
grant all on table public.game_messages to service_role;

create table if not exists public.player_blocks (
  blocker_user_id uuid not null references auth.users(id) on delete cascade,
  blocked_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_user_id, blocked_user_id),
  check (blocker_user_id <> blocked_user_id)
);

alter table public.player_blocks enable row level security;
revoke all on table public.player_blocks from public, anon, authenticated;
grant all on table public.player_blocks to service_role;

-- Reports gain the dm surface. The original check was declared inline, so its name is
-- generated; drop whichever check mentions surface rather than guessing the name.
do $$
declare
  existing record;
begin
  for existing in
    select conname from pg_constraint
    where conrelid = 'public.player_reports'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%surface%'
  loop
    execute format('alter table public.player_reports drop constraint %I', existing.conname);
  end loop;
end
$$;

alter table public.player_reports
  add constraint player_reports_surface_check
  check (surface in ('voice', 'chat', 'wall', 'drawing', 'name', 'behaviour', 'dm'));

-- The reported messages themselves. note is 300 characters and witnesses means who was in
-- earshot, so neither can hold a conversation.
alter table public.player_reports
  add column if not exists evidence jsonb not null default '[]'::jsonb;

alter table public.player_reports
  drop constraint if exists player_reports_evidence_shape;
alter table public.player_reports
  add constraint player_reports_evidence_shape
  check (jsonb_typeof(evidence) = 'array' and jsonb_array_length(evidence) <= 50);
